from enum import Enum


class TestState(Enum):
    IDLE = "IDLE"
    PREPARING = "PREPARING"
    CELL_CONFIGURING = "CELL_CONFIGURING"
    CELL_ON = "CELL_ON"
    WAITING_ATTACH = "WAITING_ATTACH"
    ATTACHED = "ATTACHED"
    MEASURING = "MEASURING"
    PAUSED = "PAUSED"
    STOPPING = "STOPPING"
    CLEANUP = "CLEANUP"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
